<?php

namespace Partage\PartageBundle\Repository;

/**
 * CuisinierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuisinierRepository extends \Doctrine\ORM\EntityRepository
{
}
