<?php

namespace Partage\PartageBundle\Repository;

/**
 * StatutAtelierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutAtelierRepository extends \Doctrine\ORM\EntityRepository
{
}
